-keep class io.github.offlineglass.hook.HookEntry { *; }
-keep class io.github.offlineglass.hook.** { *; }
-keep class io.github.offlineglass.config.SettingsProvider { *; }
-keepattributes *Annotation*
-dontwarn de.robv.android.xposed.**
